# Generated by Django 5.1.4 on 2025-01-07 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nric',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid NRIC', regex='[A-Z]\\d{7}[A-Z]')]),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wardtype',
            name='name',
            field=models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, unique=True),
        ),
    ]
